# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-01-31 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='uuid')),
                ('second_name', models.TextField(blank=True, max_length=30, verbose_name=b'\xd0\xa4\xd0\xb0\xd0\xbc\xd0\xb8\xd0\xbb\xd0\xb8\xd1\x8f')),
                ('first_name', models.TextField(blank=True, max_length=30, verbose_name='\u0418\u043c\u044f')),
                ('surname', models.TextField(blank=True, max_length=30, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('email', models.TextField(blank=True, max_length=40, verbose_name='email')),
            ],
        ),
    ]
