version: '3.8'

services:
  service:
    build:
      context: ./somedjangoproject
      dockerfile: Dockerfile
    image: service
    restart: always
    entrypoint: ./run_web.sh
    volumes:
      - static:/staticfiles:rw
    expose:
      - 8000
    env_file:
      - ./.env
    networks:
      - some_network

  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - 15672:15672
    networks:
      - some_network
  
  celery:
    build:
      context: ./somedjangoproject
      dockerfile: Dockerfile
    command: celery -A someproject worker -l info
    env_file:
      - ./.env
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRETKEY}
    networks:
      - some_network

  celery-beat:
    build:
      context: ./somedjangoproject
      dockerfile: Dockerfile
    command: celery -A someproject beat -l info
    env_file:
      - ./.env
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRETKEY}
    networks:
      - some_network
  
  nginx:
    image: nginx:1.21-alpine
    restart: always
    ports:
      - 80:80
    depends_on:
      - service
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - static:/staticfiles:ro
    networks:
      - some_network

volumes:
  static:

networks:
  some_network:
    driver: bridge